project:
  type: book
  output-dir: docs

book:
  title: "Deep R Programming Excercise Book"
  author: "David Foord"
  date: ""
  chapters:
    - index.qmd
    - intro.qmd
    - numeric.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



