project:
  type: book
  output-dir: docs

book:
  title: "Deep R Programming Exercise Book"
  author: "David Foord"
  chapters:
    - index.qmd
    - intro.qmd
    - numeric.qmd
    - logical.qmd
  navbar:
    background: navy
    foreground: white

bibliography: references.bib

format:
  html:
    theme: flatly


